
name: Create Image Tag
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tool3/bump@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          unrelated: true
